version: 2.1

#orbs:
#  aws-ecr: circleci/aws-ecr@8.1.3

jobs:
  build-astro:
    docker:
      - image: cimg/node:18.11.0
    steps:
      - checkout
      - setup_remote_docker:      
          docker_layer_caching: true
          #- restore_cache:
              #    keys:
                  #      - deps-v1--{{ "checksum my-medusa-starter/package-lock.json" }} 
                  #    - deps-v1-- 
      - run:
          name: "build astro on ec2"
          command: |
            echo $pem >> astro.pem
            echo '54.176.211.164 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBB3G/S0ZeBnvwNuSmY3E47BJKp66CBlnCQORYmVAbTR+mwUgNoJrlZo6j5HnkKQ9LqViRa/hxmUHUqiJ3FA7p60=' >> ~/.ssh/known_hosts
            chmod 400 astro.pem
            npm i && npm run build
            sudo scp -i astro.pem /home/skyler/astro/astro ubuntu@54.176.211.164:~/
            ssh -i astro.pem ubuntu@54.176.211.164 "cd ~/astro && npm i && npm run dev"
            rm -f astro.pem
            #- run:
            #name: "context variables"
            #command: echo $d_login && echo $d_pass
            #- save_cache:
            #paths:
            #-  my-medusa-starter/node-modules
            #key: deps-v1--{{ "checksum my-medusa-starter/package-lock.json" }}
workflows:
  astro_build:

    jobs:
      - build-astro:
          context: docker_login

              #scp -i .pem . ubuntu@ip:dest_path
              #ssh -i .pem "npm i; npm run build"
