version: 2.1

#orbs:
#  aws-ecr: circleci/aws-ecr@8.1.3

jobs:
  build-astro:
    docker:
      - image: cimg/node:18.11.0
    steps:
      - checkout
      - setup_remote_docker:      
          docker_layer_caching: true
          #- restore_cache:
              #    keys:
                  #      - deps-v1--{{ "checksum my-medusa-starter/package-lock.json" }} 
                  #    - deps-v1-- 
      - run:
          name: "build astro on ec2"
          command: |
            scp -i .pem . ubuntu@ip:destination
            ssh -i .pem "npm i; npm run build"
            #- run:
            #name: "context variables"
            #command: echo $d_login && echo $d_pass
            #- save_cache:
            #paths:
            #-  my-medusa-starter/node-modules
            #key: deps-v1--{{ "checksum my-medusa-starter/package-lock.json" }}
workflows:
  astro_build:

    jobs:
      - build-astro:
              #filters:
              # branches:
              #only: medusa_staging
          context: docker_login

              #scp -i .pem . ubuntu@ip:dest_path
              #ssh -i .pem "npm i; npm run build"
